### ISSUE TITLE
Kail镜像页面出现友站页面

### ISSUE THREAD

**Issue by Merrg1n** [hitlug/issues#11]
出现问题的页面 [](http://mirrors.hit.edu.cn/kali/)
截图 ![image.png](https://i.loli.net/2019/12/21/fhKgRyBUcMDpLVm.png)

**Comment by billchenchina** [comment]
😂
之所以会出现这个是因为在镜像初始化同步未完成的时候会反代 tuna 或其他镜像站来保证使用。

Fixed now.
