### ISSUE TITLE
添加anaconda镜像

### ISSUE THREAD

**Issue by Zephyroam** [hitlug/issues#13]

**Comment by billchenchina** [comment]
根据我们 2019-10-22 得到的回复

> Kumar Singh (Anaconda)
> Oct 22, 1:23 AM CDT
> 
> Hello,
> 
> Unfortunately, we don't allow public mirroring of our repo at this time.  You could only mirror our repo through our enterprise product.
> 
> I'll set the ticket as solved, if you need any additional assistance, simply reply and the ticket will automatically reopen.
> 
> Best Regards
> Kumar Singh
> Support Engineer
> anaconda.com

我们暂时并不能添加 Anaconda 镜像。

**Comment by Windaway** [comment]
感谢

**Comment by billchenchina** [comment]
anaconda 已同步完成。

https://mirrors.hit.edu.cn/anaconda/
