### ISSUE TITLE
优麒麟加入哈尔滨工业大学开源镜像站申请

### ISSUE THREAD

**Issue by fenshezhuiyi** [hitlug/issues#17]
​哈尔滨工业大学开源镜像站站长：
     您好，我是优麒麟社区妥妥（微信号：fenshezhuiyi，邮箱：contact@ubuntukylin.com），感谢您们对国内外开源软件镜像的维护，为用户提供镜像下载。优麒麟的镜像也希望申请加入贵站，不知是否有这个机会，如能够加入，我们会有相应的工作人员配合贵站同步或上传每版本发布的镜像。期待您的回复，谢谢！
关于优麒麟
     优麒麟（Ubuntu Kylin）是由麒麟软件有限公司主导开发的全球开源项目，作为Ubuntu的官方衍生版本，专注于研发“友好易用，简单轻松”的桌面环境，致力为全球用户带来更智能的用户体验，做Linux开源桌面操作系统领航者！
      优麒麟开源操作系统自2013年创建至今，已累计发行16个版本，下载量超过3000万次，向开源社区贡献代码数百万行，被 Linux、Debian、Ubuntu、OpenStack、Ceph等国际开源社区接收的 patch 超过 7000 个，在全球范围内拥有数十万活跃用户。
      UKUI 是由麒麟团队开发的基于 Linux 发行版的轻量级桌面环境，默认搭载在优麒麟开源操作系统和银河麒麟/中标麒麟商业发行版中，并支持 Ubuntu、Debian、Arch、openEuler、Fedora等国际主流Linux发行版。

优麒麟官网：http://www.ubuntukylin.com
系统下载：http://www.ubuntukylin.com/downloads/
阿里镜像站：https://mirrors.aliyun.com/ubuntukylin/
华为镜像站：https://mirrors.huaweicloud.com/ubuntukylin/
重庆大学镜像站：http://mirrors.cqu.edu.cn/UbuntuKylin_release/
360服务器：http://nudt.dl.360tpcdn.com/data/ubuntukylin-20.10-enhanced-amd64.iso

镜像同步方式：
参考用例：RSYNC_PASSWORD="user"  /usr/bin/rsync -azHv --delete --port=8873  --progress  user@service.ubuntukylin.com::rsync   ~/data
rsync同步地址: user@service.ubuntukylin.com::rsync /data

**Comment by billchenchina** [comment]
考虑到 https://github.com/ustclug/mirrorrequest/issues/219 ，正在与优麒麟方进行沟通

**Comment by billchenchina** [comment]
Update: https://mirrors.hit.edu.cn/ubuntukylin/free/
