### ISSUE TITLE
深圳校区表示也想访问

### ISSUE THREAD

**Issue by RManLuo** [hitlug/issues#2]
可否将深圳校区的ip也添加至访问名单

**Comment by ranpox** [comment]
您好，镜像站没有限制访问者的来源，域名解析的是校内网ip，我也不太清楚深圳校区能否访问哈尔滨校区的内网，我明天咨询一下网络中心。

**Comment by ranpox** [comment]
@Rman0fCN 您好，我今天咨询了本部网络中心，深圳校区访问本部网络是深圳校区网络中心操作管理的，所以需要深圳校区的同学和网络中心协商。

**Comment by leylee** [comment]
镜像站现已提供校外访问
