### ISSUE TITLE
新增openEuler镜像源的申请

### ISSUE THREAD

**Issue by zhang-jian-jun** [hitlug/issues#24]
项目名称：
openEuler镜像源

项目简介：
openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展，官网链接：https://openeuler.org/zh/

上游源地址：
https://repo.openeuler.org/

镜像同步方法：
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

镜像大小:
多个版本共600G

**Comment by GeorgeCao-hw** [comment]
@billchenchina @piggynl 
你好，我们是openEuler社区基础设施团队。
近期社区在和国内各大高校开展开源实习活动。（https://www.openeuler.org/zh/internship/ ） 
贵校有不少同学在参与该活动。所以我们希望贵站可以收入openEuler镜像，以便同学下载。
谢谢。

**Comment by billchenchina** [comment]
https://mirrors.hit.edu.cn/openeuler/

**Comment by GeorgeCao-hw** [comment]
收到，感谢~
