### ISSUE TITLE
申请添加 blackarch 镜像

### ISSUE THREAD

**Issue by Xeonacid** [hitlug/issues#33]
- 新的镜像介绍
BlackArch 是一个提供给渗透测试以及安全人员的完整的 Linux 发行版。它是 ArchLinux 的一个分支，用户可以在 ArchLinux 上安装单个或一组 BlackArch 组件。

- 上游源的地址或官方网站
https://blackarch.org/blackarch/

- 关于此镜像尽量详细的相关信息（如镜像大小，同步方法等）
76.23G `rsync://www.blackarch.org/blackarch/`
(from https://mirrors.bfsu.edu.cn/status/#syncing-status)

**Comment by piggynl** [comment]
已添加
