### ISSUE TITLE
添加 msys2 镜像

### ISSUE THREAD

**Issue by sfc9982** [hitlug/issues#34]
维护者们，您好：
### msys2 镜像
架构：
```
MINGW: i686, x86_64, ucrt64, clang64
MSYS: i686, x86_64
```
同清华源：[https://mirrors.tuna.tsinghua.edu.cn/help/msys2/](https://mirrors.tuna.tsinghua.edu.cn/help/msys2/)
官网 [https://packages.msys2.org/repos](https://packages.msys2.org/repos)

**Comment by billchenchina** [comment]
https://www.msys2.org/dev/mirrors/

**Comment by Logiase** [comment]
check http://mirrors.hit.edu.cn/msys2/

**Comment by Logiase** [comment]
同步完成

**Comment by sfc9982** [comment]
Thanks
