### ISSUE TITLE
deepin-cd无法正常工作

### ISSUE THREAD

**Issue by SDust66** [hitlug/issues#35]
deepin镜像（http://mirrors.hit.edu.cn/deepin/）可以正常访问使用，但是提供deepin安装iso文件的deepin-cd仓库（http://mirrors.hit.edu.cn/deepin-cd/）提示404，希望可以修复

**Comment by billchenchina** [comment]
因为再分发的问题，deepin-cd 中的 iso 暂时不提供下载。
