### ISSUE TITLE
ubuntu20.04桌面版sha256校验错误

### ISSUE THREAD

**Issue by vpzz** [hitlug/issues#36]
下载了两次，不知道为啥，有人有一样的问题吗？

**Comment by zsh2517** [comment]
`http://mirrors.hit.edu.cn/ubuntu-releases/20.04/ubuntu-20.04.3-desktop-amd64.iso` 吗？

我试了一下，和 Mirrors [SHA256SUMS](http://mirrors.hit.edu.cn/ubuntu-releases/20.04/SHA256SUMS) 以及 ubuntu 官方 SHA256 值均相同

如果不同的话，方便提供一下下载链接和校验值吗？

```shell
➜  temp wget http://mirrors.hit.edu.cn/ubuntu-releases/20.04/ubuntu-20.04.3-desktop-amd64.iso
--2021-12-23 22:43:44--  http://mirrors.hit.edu.cn/ubuntu-releases/20.04/ubuntu-20.04.3-desktop-amd64.iso
Resolving mirrors.hit.edu.cn (mirrors.hit.edu.cn)... 202.118.254.110
Connecting to mirrors.hit.edu.cn (mirrors.hit.edu.cn)|202.118.254.110|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3071934464 (2.9G) [application/octet-stream]
Saving to: ‘ubuntu-20.04.3-desktop-amd64.iso’

ubuntu-20.04.3-desktop-amd64. 100%[=================================================>]   2.86G  42.0MB/s    in 50s

2021-12-23 22:44:34 (58.6 MB/s) - ‘ubuntu-20.04.3-desktop-amd64.iso’ saved [3071934464/3071934464]

➜  temp sha256sum ubuntu-20.04.3-desktop-amd64.iso
5fdebc435ded46ae99136ca875afc6f05bde217be7dd018e1841924f71db46b5  ubuntu-20.04.3-desktop-amd64.iso

➜  temp curl http://mirrors.hit.edu.cn/ubuntu-releases/20.04/SHA256SUMS
5fdebc435ded46ae99136ca875afc6f05bde217be7dd018e1841924f71db46b5 *ubuntu-20.04.3-desktop-amd64.iso
f8e3086f3cea0fb3fefb29937ab5ed9d19e767079633960ccb50e76153effc98 *ubuntu-20.04.3-live-server-amd64.iso
```

**Comment by sfc9982** [comment]
我这边验证SHA256没有问题，您再试试？

**Comment by sfc9982** [comment]
重启或者清空下载缓存试试？

**Comment by liuxhit** [comment]
![image](https://user-images.githubusercontent.com/23427350/147258310-c80c071b-9aaf-41b6-83cd-125b9bb1197a.png)

**Comment by keuin** [comment]
我检查了 [ubuntu-20.04.3-desktop-amd64.iso](https://mirrors.hit.edu.cn/ubuntu-releases/focal/ubuntu-20.04.3-desktop-amd64.iso)，他的sha256和官网给的一致（[https://releases.ubuntu.com/20.04/SHA256SUMS](https://releases.ubuntu.com/20.04/SHA256SUMS)）

**Comment by vpzz** [comment]
破案了，是我的下载器有问题，用的是FDM，之前别的镜像都没出现过这种问题，不过以前都是在清华下载的。

我一开始以为是地址的问题，我是从网站右边的获取下载链接里下载的，链接是 http://mirrors.hit.edu.cn/ubuntu-releases/focal/ubuntu-20.04.3-desktop-amd64.iso
我看了下从网站最下面的目录进去，链接是 http://mirrors.hit.edu.cn/ubuntu-releases/20.04/ubuntu-20.04.3-desktop-amd64.iso

于是我怀疑是focal和20.04的问题，结果用FDM下载了一遍，发现这俩都不一样，还都和官方的校验对不上（下面附上两个图）![20 04校验](https://user-images.githubusercontent.com/18623657/147283772-13647a9f-f358-44c1-a9f5-2b8a3f55d569.png)
![focal的校验](https://user-images.githubusercontent.com/18623657/147283775-c19332b4-5e54-4dd5-af12-7e802780b809.png)。我还到镜像文件里边溜达了一圈，发现其中有个2个多G的文件 ./casper/filesystem.squashfs 的校验出错了。

后来我寻思有没有可能是下载器的问题，我就用Chrome下载了一下，结果focal和20.04都没问题了，校验都通过。

我再研究一下FDM是咋回事。。。

------------
刚才又用FDM去清华源试了下，校验没问题，有点蒙了。

**Comment by billchenchina** [comment]
> 破案了，是我的下载器有问题，用的是FDM，之前别的镜像都没出现过这种问题，不过以前都是在清华下载的。

一个猜测，不一定对，把 URL 修正成 https 的试试看？会不会是运营商缓存？

> 后来我寻思有没有可能是下载器的问题，我就用Chrome下载了一下，结果focal和20.04都没问题了，校验都通过。
> 
> 我再研究一下FDM是咋回事。。。
> 
> 刚才又用FDM去清华源试了下，校验没问题，有点蒙了。

FDM 应该不至于有问题？我找时间试试看 FDM...

**Comment by vpzz** [comment]
@billchenchina 
> 一个猜测，不一定对，把 URL 修正成 https 的试试看？会不会是运营商缓存？

用FDM试了下https的，校验没问题了。我发现百度收录的是http地址。试了下网站也支持https访问，以后就用https了。
