### ISSUE TITLE
Request for mirroring debian-ports

### ISSUE THREAD

**Issue by keuin** [hitlug/issues#49]
Please consider adding [debian-ports](http://ftp.ports.debian.org/debian-ports/), which is an apt repository that contains packages built for some architectures other than x86/64 ones, such as RISC-V. RISC-V is a promising RISC instruction set. Researchers and engineers have made great progress on this arch in recent years.

Just FYI, SJTUG is maintaining a debian-ports mirror on their mirror server (<https://mirror.sjtu.edu.cn/debian-ports/>), which is RISC-V only. It might be too expensive to synchronize the full repo.

**Comment by billchenchina** [comment]
Mirror sync in progress: https://mirrors.hit.edu.cn/debian-ports/

**Comment by billchenchina** [comment]
```
deb http://mirrors.hit.edu.cn/debian-ports unstable main contrib non-free non-free-firmware
deb-src http://mirrors.hit.edu.cn/debian-ports unstable main contrib non-free non-free-firmware

deb http://mirrors.hit.edu.cn/debian-ports experimental main contrib non-free non-free-firmware
deb-src http://mirrors.hit.edu.cn/debian-ports experimental main contrib non-free non-free-firmware
```
