### ISSUE TITLE
增加Eclipse镜像

### ISSUE THREAD

**Issue by idrey** [hitlug/issues#5]
希望镜像站能够增加`Eclipse`的镜像，具体信息请见[https://www.eclipse.org/downloads/mir_request.php](https://www.eclipse.org/downloads/mir_request.php)

**Comment by billchenchina** [comment]
已经开始处理。

**Comment by billchenchina** [comment]
已添加。

您可以通过右侧下载链接处直接下载。
![image](https://user-images.githubusercontent.com/7758042/70218705-75ece900-177e-11ea-83d6-090fa408cc36.png)
