### ISSUE TITLE
Ubuntu jammy amd64 apt配置文件hash值错误

### ISSUE THREAD

**Issue by Yastruhank** [hitlug/issues#52]
在使用apt update时出现以下报错:
#0 7.628 Get:27 http://mirrors.hit.edu.cn/ubuntu jammy-updates/universe amd64 Packages [1131 kB]
#0 7.878 Err:27 http://mirrors.hit.edu.cn/ubuntu jammy-updates/universe amd64 Packages
#0 7.878   Hash Sum mismatch
#0 7.878   Hashes of expected file:
#0 7.878    - Filesize:1131003 [weak]
#0 7.878    - SHA256:7c7eb7f4cf922f4f0c5f9c4e07b4350a719f0424d18935597dffb83e1c785032
#0 7.878    - SHA1:c88f27f738cb370d37cac6318581f3ec3de6185c [weak]
#0 7.878    - MD5Sum:510d4bc70751c3337ca47b7ba7d669e5 [weak]
#0 7.878   Hashes of received file:
#0 7.878    - SHA256:b20e33b99c7b18f4d2eec6876f421b1a963a5e012f1f0b7799063f42a50dc259
#0 7.878    - SHA1:5523a9f022cd5f5ffca54ed88de2a2e09bab0aeb [weak]
#0 7.878    - MD5Sum:4ada0503160add2291761ee979c6d3c4 [weak]
#0 7.878    - Filesize:1131003 [weak]
#0 7.878   Last modification reported: Wed, 15 Mar 2023 01:56:17 +0000
#0 7.878   Release file created at: Wed, 15 Mar 2023 06:26:43 +0000
在使用其它镜像源时正常，应该是相关配置文件hash值出错

**Comment by billchenchina** [comment]
这个应该是因为正在同步中，等一等呢？

**Comment by billchenchina** [comment]
看了一下我这里没问题，如果依然有问题的话可以 reopen 这个 issue 然后继续回复。
