### ISSUE TITLE
能否开设一个vscode的镜像

### ISSUE THREAD

**Issue by Mactarvish** [hitlug/issues#55]
国内下载vscode特别慢，如果开一个vscode的镜像应该会有很大帮助。谢谢。

**Comment by piggynl** [comment]
Visual Studio Code 的许可证不允许再分发二进制软件包。

<https://code.visualstudio.com/license?lang=en>

> **SCOPE OF LICENSE.** This license applies to the Visual Studio Code product. Source code for Visual Studio Code is available at https://github.com/Microsoft/vscode under the MIT license agreement. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement. In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways. You may not
>
> - ...
> - share, publish, rent or lease the software, or provide the software as a stand-alone offering for others to use.

**Comment by wuzhenqing** [comment]
Adding mirrors for VS Code would involve licensing issues, so perhaps a proposal could be made to add mirrors for VS Codium. Also for the slow download of VS Code, you seem to be not using the CDN correctly to speed up your downloads, which are usually very fast on my computer without using a VPN.

**Comment by billchenchina** [comment]
> Also for the slow download of VS Code, you seem to be not using the CDN correctly to speed up your downloads, which are usually very fast on my computer without using a VPN.

嗯，我记得 msedge 是有中国 cdn 的？
