### ISSUE TITLE
新增 Virtualbox 安装程序及扩展包镜像

### ISSUE THREAD

**Issue by Drickle** [hitlug/issues#6]
Oracle VM VirtualBox 是一款开源的虚拟机软件。

- 官网： https://www.virtualbox.org/
- 下载服务器： https://download.virtualbox.org/virtualbox/

如果觉得镜像大小过大，可以考虑镜像清华的镜像。（我实在找不到镜像的协议和方法，正在邮件联系）

**Comment by billchenchina** [comment]
那个...不用邮件联系...
https://github.com/tuna/tunasync-scripts/blob/master/virtualbox.sh

**Comment by billchenchina** [comment]
已添加。
