### ISSUE TITLE
关于anaconda页面文档的重大纰漏

### ISSUE THREAD

**Issue by JoeLee-TQXTC** [hitlug/issues#62]
页面：[https://mirrors.hit.edu.cn/#/doc/anaconda](https://mirrors.hit.edu.cn/#/doc/anaconda)
![image](https://github.com/user-attachments/assets/3862eb6b-b997-40d1-aeba-9cc12eb2deab)
如上图
快去改吧，，，我真认识tuna的人。。。。还没跟他们说

**Comment by billchenchina** [comment]
https://github.com/hitlug/mirror-web/blob/master/src/components/docPage/doc/markdown/anaconda.md
你可以提个 PR 嘛？

**Comment by JoeLee-TQXTC** [comment]
> https://github.com/hitlug/mirror-web/blob/master/src/components/docPage/doc/markdown/anaconda.md 你可以提个 PR 嘛？

明儿早八，周末有空了再说吧，提了的话会在这里回复

**Comment by billchenchina** [comment]
> 明儿早八，周末有空了再说吧，提了的话会在这里回复

感谢~ 也欢迎来 lug qq 群玩~ 702339456
