### ISSUE TITLE
Gentoo Portage rsync mirror

### ISSUE THREAD

**Issue by 12101111** [hitlug/issues#7]
- description: Rsync (Portage tree) mirrors distribute the main Gentoo ebuild repository to users.
- upstream: https://www.gentoo.org/support/rsync-mirrors/
- setup: https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Rsync
- size: ~692M

PS: Don't be confused with [Gentoo Source (distfile) mirrors](https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Source)

**Comment by billchenchina** [comment]
Added.
http://mirrors.hit.edu.cn/gentoo-portage/

**Comment by billchenchina** [comment]
rsyncd configured.
