### ISSUE TITLE
增加elpa镜像

### ISSUE THREAD

**Issue by mortis-0** [hitlug/issues#8]

**Comment by wineee** [comment]
补充同步方法（摘自emacs-china）

用 Rsync 同步本镜像(emacs-china)
整个镜像约占 1 GB，地址为：

  rsync://elpa.emacs-china.org/elpa/
下游 Tsinghua Mirrors 的 ELPA 镜像 也提供了 Rsync 服务，地址是：

  rsync://mirrors.tuna.tsinghua.edu.cn/elpa/
上游 GNU ELPA 和 MELPA 提供了 Rsync 服务，其地址分别为：

  rsync://elpa.gnu.org/elpa/
  rsync://melpa.org/packages/

**Comment by billchenchina** [comment]
已同步
