### ISSUE TITLE
发行版镜像下载中Debian全系下载链接均为404错误

### ISSUE THREAD

**Issue by mortis-0** [hitlug/issues#9]
镜像文件的确存在但是链接生成有误:
这是实际的链接:
http://mirrors-hit-edu-cn.ivpn.hit.edu.cn/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.2.0-amd64-lxde.iso
这是生成的链接:
http://mirrors-hit-edu-cn.ivpn.hit.edu.cn/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.1.0-amd64-lxde.iso
似乎是搞错了Debian的版本号

**Comment by billchenchina** [comment]
现在版本号不是动态维护的...是在 https://github.com/hitlug/mirror-web/blob/master/public/static/isoLinks.json 指定的。

过几天会做一下动态更新。

**Comment by billchenchina** [comment]
Fixed now.
